### ISSUE TITLE
[A12] Crash when clicking on Fullscreen

### ISSUE THREAD

**Issue by FireMasterK** [rimthekid/LibreTube#1]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xyz.btcland.libretube, PID: 4871
    java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.constraintlayout.motion.widget.MotionScene$Transition.setEnabled(boolean)' on a null object reference
        at androidx.constraintlayout.motion.widget.MotionLayout.enableTransition(MotionLayout.java:1165)
        at xyz.btcland.libretube.PlayerFragment.onViewCreated$lambda-6(PlayerFragment.kt:193)
        at xyz.btcland.libretube.PlayerFragment.$r8$lambda$IO68uyAF1JBuw8jqOpeQtFHXv4k(Unknown Source:0)
        at xyz.btcland.libretube.PlayerFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28677)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7835)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by FireMasterK** [comment]
Closing as it doesn't occour with be894365b1144ad308ca1b24948bc5a6682b38c5 now.
